---
before_install:
  - gem update --system
  - gem --version
language: ruby
notifications:
  email:
    - mike@blowmage.com
rvm:
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
env:
  - "RAILS_VERSION=4.1"
